### ISSUE TITLE
Morning Code Review

### ISSUE THREAD

**Issue by AlejandroNeira98** [VicPeralta/to-Do-List#12]
Hello Victor, 
First of all, I want to congratulate you on your amazing work, I can see that you are very dedicated and organized 🥇 
Second of all, I want to thank you for walking me through your code because that helped me to improve my knowledge on the JavaScript best practices and on the OOP methods in JS 👍
Finally, there's nothing else to say to you, your code is very clean and optimized, very good work applying all the best practices.

**Comment by VicPeralta** [comment]
Thank you very much for your comments
