### ISSUE TITLE
Morning sessions code review

### ISSUE THREAD

**Issue by AlejandroNeira98** [VicPeralta/to-Do-List#15]
Hello Victor, 
I want to tell you that your code is amazingly well organized and very clean. It's great to see the amount of work that you have dedicated to your learning process 🥇 Now, as a way of improving the only thing that I have to say to you is that when you choose a name for a variable try to name it with a semantic value so that other people, and even you in the future, can read and understand the purpose and the content of your variables in an easier way.

**Comment by VicPeralta** [comment]
Thanks for your review. I will definitely follow your advice.
